version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: schoolmaster_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: school_master
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d school_master"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: schoolmaster_redis
    command: redis-server --requirepass redispass --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redispass", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: schoolmaster_app
    entrypoint: ["python", "/entrypoint.py"]  # ✅ só aqui
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg://user:password@db:5432/school_master
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: user
      DB_PASS: password
      DB_NAME: school_master
      REDIS_URL: redis://:redispass@redis:6379/0
    ports:
      - "8000:8000"

  celery_worker:
    build: .
    container_name: schoolmaster_celery_worker
    command: celery -A app.core.celery worker --loglevel=info
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg://user:password@db:5432/school_master
      REDIS_URL: redis://:redispass@redis:6379/0
    volumes:
      - .:/app

  flower:
    build: .
    container_name: schoolmaster_flower
    command: celery -A app.core.celery flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://:redispass@redis:6379/0

volumes:
  postgres_data:
  redis_data: