from app.models.usuario import Usuario
from app.models.funcionario import Funcionario
from app.models.professor import Professor
from app.models.disciplina import Disciplina
from app.models.professor_disciplina import ProfessorDisciplina
from app.models.turma import Turma
from app.models.turma_professores import TurmaProfessores
from app.models.aluno import Aluno
from app.models.role import Role
from app.models.audit_log import AuditLog
from app.models.frequencia import Frequencia
from app.models.role_permissions import RolePermission
from app.models.aluno_responsavel import AlunoResponsavel